!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  cluster_max_height: 0.09
  cluster_max_length: 0.25
  cluster_max_size: 2147483647
  cluster_min_distance_to_polygon: 0.03
  cluster_min_height: 0.011
  cluster_min_size: 10
  cluster_tolerance: 0.05
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      cluster_max_height: 0.09
      cluster_max_length: 0.25
      cluster_max_size: 2147483647
      cluster_min_distance_to_polygon: 0.03
      cluster_min_height: 0.011
      cluster_min_size: 10
      cluster_tolerance: 0.05
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      normal_radius_search: 0.035
      object_height_above_workspace: 0.03
      outlier_min_neighbors: 5
      outlier_radius_search: 0.1
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      passthrough_filter_field_name: z
      passthrough_filter_limit_max: 0.8
      passthrough_filter_limit_min: -0.04
      prism_max_height: 5.0
      prism_min_height: 0.007
      sac_distance_threshold: 0.02
      sac_eps_angle: 0.17
      sac_max_iterations: 50
      sac_normal_distance_weight: 0.1
      sac_optimize_coefficients: true
      state: true
      type: ''
      voxel_filter_field_name: z
      voxel_filter_limit_max: 0.25
      voxel_filter_limit_min: -0.04
      voxel_leaf_size: 0.009
    state: []
  normal_radius_search: 0.035
  object_height_above_workspace: 0.03
  outlier_min_neighbors: 5
  outlier_radius_search: 0.1
  passthrough_filter_field_name: z
  passthrough_filter_limit_max: 0.8
  passthrough_filter_limit_min: -0.04
  prism_max_height: 5.0
  prism_min_height: 0.007
  sac_distance_threshold: 0.02
  sac_eps_angle: 0.17
  sac_max_iterations: 50
  sac_normal_distance_weight: 0.1
  sac_optimize_coefficients: true
  voxel_filter_field_name: z
  voxel_filter_limit_max: 0.25
  voxel_filter_limit_min: -0.04
  voxel_leaf_size: 0.009
state: []
