# reasonable parameters to find planes of @Work workspaces
scene_segmentation:
    voxel_leaf_size: 0.0025
    passthrough_limit_min_x: 0.0
    passthrough_limit_max_x: 0.8
    passthrough_limit_min_y: -0.5
    passthrough_limit_max_y: 0.5
    voxel_limit_min_z: -0.15
    voxel_limit_max_z: 0.3
    normal_radius_search: 0.03
    sac_max_iterations: 1000
    sac_distance_threshold: 0.01
    sac_optimize_coefficients: true
    sac_eps_angle: 0.09
    sac_normal_distance_weight: 0.05
    prism_min_height: 0.01
    prism_max_height: 0.1
    outlier_radius_search: 0.03
    outlier_min_neighbors: 20
    cluster_tolerance: 0.02
    cluster_min_size: 25
    cluster_max_size: 20000
    cluster_min_height: 0.011
    cluster_max_height: 0.09
    cluster_max_length: 0.25
    cluster_min_distance_to_polygon: 0.04
    octree_resolution: 0.0025
    object_height_above_workspace: 0.052
    rgb_container_height: 0.0335
    rgb_bbox_size_adjustment: 2
    rgb_bbox_min_diag: 21
    rgb_bbox_max_diag: 175
    rgb_cluster_filter_limit_min: 0.009
    rgb_cluster_filter_limit_max: 0.35
    rgb_base_link_to_laser_distance: 0.350
    rgb_max_object_pose_x_to_base_link: 0.650
    rgb_min_bbox_z: 0.03
