global_costmap:
  global_frame: /map                #default : odom
  robot_base_frame: base_footprint  #default : "base_link"
  update_frequency: 5.0             #default : 5.0
  static_map: true                  #default : true
