local_costmap:
  global_frame: /map                    #default : "/map"
  robot_base_frame: base_footprint      #default : "base_link"
  update_frequency: 5.0                 #default : 5.0
  publish_frequency: 0.0                #default : 0.0
  static_map: false                     #default : true
  rolling_window: true                  #default : false
  width: 10.0                           #default : 10
  height: 6.0                           #default : 10
  resolution: 0.04                      #default : 0.05
