local_costmap:
  global_frame: /map                    #_default : "/map"
  inflation_radius: 0.43                #_default: 0.55
  robot_base_frame: base_footprint      #default : "base_link"
  update_frequency: 1.0                 #_default : 5.0
  publish_frequency: 1.5                #_default : 0.0
  static_map: false                     #default : true
  rolling_window: true                  #_default : false
  width: 2.5                            #_default : 10
  height: 2.5                           #_default : 10
  resolution: 0.04                      #default : 0.05

#================================================  
# (Documentation available at http://wiki.ros.org/costmap_2d?distro=hydro)
# --------------------------------------------------------
# global_frame: The global frame for the costmap to operate in
# default : "/map"
# --------------------------------------------------------
# inflation_radius: The radius in meters to which the map inflates obstacle cost values
# default: 0.55
# --------------------------------------------------------
# robot_base_frame: The name of the frame for the base link of the robot
# default : "base_link"
# --------------------------------------------------------
# update_frequency: The frequency in Hz for the map to be updated
# default : 5.0
# --------------------------------------------------------
# publish_frequency: The frequency in Hz for the map to be publish display information
# default : 0.0
# --------------------------------------------------------
# static_map: Whether or not to use the static map to initialize the costmap. 
# If the rolling_window parameter is set to true, this parameter must be set to false
# default : true
# --------------------------------------------------------
# rolling_window: Whether or not to use a rolling window version of the costmap. 
# If the static_map parameter is set to true, this parameter must be set to false
# default : false
# --------------------------------------------------------
# width: The width of the map in meters
# default : 10.0
# --------------------------------------------------------
# height: The height of the map in meters
# default : 10
# --------------------------------------------------------
# resolution: The resolution of the map in meters/cell
# default : 0.05