# Documentation available at http://wiki.ros.org/move_base

# --------------------------------------------------------
# controller_frequency: The rate in Hz at which to run 
# the control loop and send velocity commands to the base
# default : 20.0

controller_frequency: 20.0

# --------------------------------------------------------
# controller_patience: How long the controller will wait in seconds 
# without receiving a valid control before space-clearing operations are performed.
# default : 15.0

controller_patience: 2.0

# --------------------------------------------------------
# planner_patience: How long the planner will wait in seconds 
# in an attempt to find a valid plan before space-clearing operations are performed
# default : 5.0

planner_patience: 2.0

# --------------------------------------------------------
# planner_frequency: The rate in Hz at which to run the global planning loop. 
# If the frequency is set to 0.0, the global planner will only run when a new goal 
# is received or the local planner reports that its path is blocked
# default : 0.0

planner_frequency: 2.0

# --------------------------------------------------------
# clearing_rotation_allowed: Determines whether or not the robot will attempt 
# an in-place rotation when attempting to clear out space. 
# Note: This parameter is only used when the default recovery behaviors are in use,
# meaning the user has not set the recovery_behaviors parameter to anything custom
# default : true

clearing_rotation_allowed: false

# --------------------------------------------------------
# oscillation_distance: 
# How far in meters the robot must move to be considered not to be oscillating. 
# Moving this far resets the timer counting up to the ~oscillation_timeout
# default : 0.5

oscillation_distance: 2.0

# --------------------------------------------------------
# Determines whether or not to shutdown the costmaps of the node 
# when move_base is in an inactive state
# default : false

shutdown_costmaps: true

# --------------------------------------------------------
# recovery_behavior_enabled: Whether or not to enable 
# the move_base recovery behaviors to attempt to clear out space
# default : true

recovery_behavior_enabled: true

# ---------NOT IN MOVE BASE !!----------------------------

# --------------------------------------------------------
# footprint_padding: not under move_base
# default : not found

footprint_padding: 0.03

# --------------------------------------------------------
# clearing_radius: not under move base
# default : not found

clearing_radius: 0.25